# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a38c1364d3a83de92175fa66bab7f3cd228d069dbc8a3e8490613688ae20952e16bd7ae48c47289e9d3ed01a43343e120b47ca88f98fe49f0766eec1fdec213

test:
  secret_key_base: 159c7bbb01e8dd7fd79fa09ee0e13cd727a431b23702ab5c898955ecaef49dadf8975aea8d1f594e417eabba610c511e5f528db21c91fa209550868e35b07773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
